pelican = '/path/to/bin/pelican'
repodir = '/path/to/repo/'
sitedir = '/path/to/repo/site'
outputdir = '/other/path/to/www'
settings_file = '/path/to/repo/site/pelicanconf.py'
log_file = '/other/path/to/www/log.txt'
gitlab_token = 'secret_token'